#Appenders:
#  Console:  #输出到控制台
#    name: CONSOLE #Appender命名
#    target: SYSTEM_OUT
#    PatternLayout:
#      pattern: "%d{yyyy-MM-dd HH:mm:ss,SSS}:%4p %t (%F:%L) - %m%n"
#  RollingFile: # 输出到文件，超过256MB归档
#    - name: ROLLING_FILE
#      ignoreExceptions: false
#      fileName: D:/ideaspace/bootDemo4/log/log.log
#      filePattern: "C:/Users/Administrator/Desktop/log -%d{yyyy-MM-dd}-%i.log.gz"
#      PatternLayout:
#        pattern: "%d{yyyy-MM-dd HH:mm:ss,SSS}:%4p %t (%F:%L) - %m%n"
#      Policies:
#        SizeBasedTriggeringPolicy:
#          size: "256 MB"
#      DefaultRolloverStrategy:
#        max: 1000
#Loggers:
#  Root:
#    level: info
#    AppenderRef:
#      - ref: CONSOLE
#  Logger: #单独设置某些包的输出级别
#    - name: app.com.kenho.mapper #复数加上-
#      additivity: false #去除重复的log
#      level: trace
#      AppenderRef:
#        - ref: CONSOLE #复数加上-
#        - ref: ROLLING_FILE #复数加上-

Configuration:
  status: warn

  Properties: # 定义全局变量
    Property: # 缺省配置（用于开发环境）。其他环境需要在VM参数中指定，如下：
      #测试：-Dlog.level.console=warn -Dlog.level.xjj=trace
      #生产：-Dlog.level.console=warn -Dlog.level.xjj=info
      - name: log.level.console
        value: trace
      - name: log.level.xjj
        value: trace
      - name: log.path
        value: D:/ideaspace/bootDemo4/log/log.log
      - name: project.name
        value: bootDemo4

  Appenders:
    Console:  #输出到控制台
      name: CONSOLE
      target: SYSTEM_OUT
      ThresholdFilter:
        level: ${sys:log.level.console} # “sys:”表示：如果VM参数中没指定这个变量值，则使用本文件中定义的缺省全局变量值
        onMatch: ACCEPT
        onMismatch: DENY
      PatternLayout:
        pattern: "%d{yyyy-MM-dd HH:mm:ss,SSS}:%4p %t (%F:%L) - %m%n"
    RollingFile: # 输出到文件，超过128MB归档
      - name: ROLLING_FILE
        ignoreExceptions: false
        fileName: ${log.path}/${project.name}.log
        filePattern: "${log.path}/$${date:yyyy-MM}/${project.name}-%d{yyyy-MM-dd}-%i.log.gz"
        PatternLayout:
          pattern: "%d{yyyy-MM-dd HH:mm:ss,SSS}:%4p %t (%F:%L) - %m%n"
        Policies:
          SizeBasedTriggeringPolicy:
            size: "128 MB"
        DefaultRolloverStrategy:
          max: 1000

  Loggers:
    Root:
      level: info
      AppenderRef:
        - ref: CONSOLE
        - ref: ROLLING_FILE
    Logger: # 为com.xjj包配置特殊的Log级别，方便调试
      - name: com.xjj
        additivity: false
        level: ${sys:log.level.xjj}
        AppenderRef:
          - ref: CONSOLE
          - ref: ROLLING_FILE
